%stoyanov formula slide p.540
% xi: probability
% alpha: parameter to define ss(alpha, 0, 1)
function ES=ES_stoy(pd,xi,alpha)
    q=icdf(pd,xi);
    disp("q= " + q);
    g = @(theta) ( ...
        sin((alpha-2)*theta) ./ sin(alpha .* theta) ...
        - ...
        alpha .* ((cos(theta)).^2) ./ (sin(alpha .* theta)) .^2 ...
        );
    v = @(theta) ( ...
        cos(theta) ./ sin(alpha .* theta)) .^ (alpha/(alpha-1)) ...
            .* cos((alpha-1)*theta) ./ cos(theta);
    fun=@(c,theta) (g(theta) .* exp( - abs(c) .^ (alpha/(alpha-1)) .* v(theta)) );
    stoy= alpha/(alpha-1) * abs(q) / pi * integral(@(theta) fun(q,theta),0,pi/2);
    ES=1/xi * stoy;    
end